### ISSUE TITLE
Can't find AdUnitManager in GreedyGame Top menu option

### ISSUE THREAD

**Issue by idzDeveloper** [GreedyGame/unity-plugin#17]
In your tutorial(Readme) you mention 
> In top menu goto GreedyGame then AdUnitManager and use panel.greedygame.com's credential to login.

But after importing unity package I can't find AdUnitManager in GreedyGame menu. I am having only 4 options those are Export Pngs, GreedyGameConfigPrefab, CreateAndroidXML, About.
Can please check and let me know where is these AdUnitManager option

**Comment by arinkverma** [comment]
@idzDeveloper 
AdUnitManager option have been removed in SDK 8.0 onwards. 
Readme updated and removed irrelevant mentions.  
If you face any other problem please let us know.
